title: Bird watch website
hero_image: images/banner.png
description: Make a unique website and style it with CSS!
listed: false
copyedit: false
pdf: false
landing: true
steps:
  - title: Code your first website!
  - title: Your own message
    completion:
      - engaged
  - title: Make a heading
  - title: Style some text
  - title: Style the background with CSS
  - title: Style the text with CSS
  - title: Style the heading
  - title: Add images
  - title: Change the image
  - title: Make a list
  - title: Add a new page
  - title: Add a nav bar
    completion:
      - internal
  - title: Style your nav bar
    completion:
      - external
  - title: Challenge
    challenge: true
